---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: backend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # for debug connection
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: LoadBalancer