FROM golang:1.21-alpine as builder

RUN mkdir /app
COPY . /app
WORKDIR /app
RUN CGO_ENABLED=0 go build -o mailAPP ./cmd/api

RUN chmod +x /app/mailAPP

FROM alpine:latest
RUN mkdir /app
COPY --from=builder /app/mailAPP /app
EXPOSE 80
CMD ["/app/mailAPP"]