apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: auth-app
  name: auth-app
  namespace: app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 80
  selector:
    app: auth-app
  type: LoadBalancer
status:
  loadBalancer: {}
