---
apiVersion: v1
kind: Service
metadata:
  name: logger-service
  namespace: app
  labels:
    app: logger-service
spec:
  selector:
    app: logger-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
  type: ClusterIP 
