FROM golang:1.21-alpine as builder

RUN mkdir /app
COPY . /app
WORKDIR /app
RUN CGO_ENABLED=0 go build -o logerApp ./cmd/api

RUN chmod +x /app/logerApp

FROM alpine:latest
RUN mkdir /app
COPY --from=builder /app/logerApp /app
EXPOSE 80
CMD ["/app/logerApp"]