name: broker-app

on:
  push:
    branches: [ "main" ]
    paths:
      - "broker-service/**"
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub 
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./broker-service/dockerfile
        push: true
        tags: darwimroy1900/micro-broker:latest
        platforms: linux/amd64,linux/arm64

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}